platform :ios, '12.0'

target 'HelpBotDemo' do
  use_frameworks!
  
  # Cocos2d-x 会通过 Xcode 项目直接链接
  # 这里只需要添加额外的依赖
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
